# Generated by Django 2.2.2 on 2019-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190619_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=30, null=True)),
                ('last_name', models.CharField(help_text='last name', max_length=30, null=True)),
            ],
        ),
    ]
