# Generated by Django 2.2.2 on 2019-06-19 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(help_text='instrument', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='generated unique id  for book', primary_key=True, serialize=False, verbose_name='Book Id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='first_name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='last_name', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(help_text='release_date', max_length=20, null=True)),
                ('artist', models.ForeignKey(help_text='artist', max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Musician')),
            ],
        ),
    ]
